[project]
name = "synth4bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0.0",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
    "setuptools>=82.0.1",
    "tensorboard>=2.20.0",
    "tensorboardx>=2.6.5",
    "xgboost>=3.1.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
